version: "3"


services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mysqldb
      TZ: Asia/Seoul

    volumes:
      - /mnt/hdd0/db/mysql/data:/var/lib/mysql
      - /mnt/hdd0/db/mysql/config:/etc/mysql/conf.d
      - /mnt/hdd0/db/mysql/init:/docker-entrypoint-initdb.d
